version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/src
    ports:
      - 8000:8000
    tty: true
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 33306:3306
